/**
 Copyright (c) 2011 Daniele Biagi
Permission is hereby granted, free of charge, to any person obtaining a copy of this 
software and associated documentation files (the "Software"), to deal in the Software 
without restriction, including without limitation the rights to use, copy, modify, 
merge, publish, distribute, sublicense, and/or sell copies of the Software, and to 
permit persons to whom the Software is furnished to do so, subject to the following 
conditions:

The above copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE 
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE 
OR OTHER DEALINGS IN THE SOFTWARE.
 */
package parser;
/* Generated By:JavaCC: Do not edit this line. EasyDLXParserConstants.java */



/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EasyDLXParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LABELJ = 86;
  /** RegularExpression Id. */
  int LABEL_COLON = 87;
  /** RegularExpression Id. */
  int NUMBER = 88;
  /** RegularExpression Id. */
  int DIGIT = 89;
  /** RegularExpression Id. */
  int COMMA = 90;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 91;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 92;
  /** RegularExpression Id. */
  int SIGN = 93;
  /** RegularExpression Id. */
  int SEMICOLON = 94;
  /** RegularExpression Id. */
  int LETTER = 95;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"ADD\"",
    "\"ADDU\"",
    "\"SUB\"",
    "\"SUBU\"",
    "\"MULT\"",
    "\"MULTU\"",
    "\"DIV\"",
    "\"DIVU\"",
    "\"AND\"",
    "\"OR\"",
    "\"XOR\"",
    "\"SLL\"",
    "\"SRL\"",
    "\"SLT\"",
    "\"SGT\"",
    "\"SLE\"",
    "\"SGE\"",
    "\"SEQ\"",
    "\"SNE\"",
    "\"ADDI\"",
    "\"ADDUI\"",
    "\"SUBI\"",
    "\"SUBUI\"",
    "\"ANDI\"",
    "\"ORI\"",
    "\"XORI\"",
    "\"SLLI\"",
    "\"SRLI\"",
    "\"SLTI\"",
    "\"SGTI\"",
    "\"SLEI\"",
    "\"SGEI\"",
    "\"SEQI\"",
    "\"SNEI\"",
    "\"LB\"",
    "\"LBU\"",
    "\"LH\"",
    "\"LHU\"",
    "\"LW\"",
    "\"SB\"",
    "\"SH\"",
    "\"SW\"",
    "\"BEQZ\"",
    "\"BNEZ\"",
    "\"JR\"",
    "\"JALR\"",
    "\"J\"",
    "\"JAL\"",
    "\"NOP\"",
    "\"R0\"",
    "\"R1\"",
    "\"R2\"",
    "\"R3\"",
    "\"R4\"",
    "\"R5\"",
    "\"R6\"",
    "\"R7\"",
    "\"R8\"",
    "\"R9\"",
    "\"R10\"",
    "\"R11\"",
    "\"R12\"",
    "\"R13\"",
    "\"R14\"",
    "\"R15\"",
    "\"R16\"",
    "\"R17\"",
    "\"R18\"",
    "\"R19\"",
    "\"R20\"",
    "\"R21\"",
    "\"R22\"",
    "\"R23\"",
    "\"R24\"",
    "\"R25\"",
    "\"R26\"",
    "\"R27\"",
    "\"R28\"",
    "\"R29\"",
    "\"R30\"",
    "\"R31\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LABELJ>",
    "<LABEL_COLON>",
    "<NUMBER>",
    "<DIGIT>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<SIGN>",
    "\";\"",
    "<LETTER>",
  };

}
